name: Update Map

permissions:
  contents: write

on:
  workflow_call:
    secrets:
      token:
        required: true

env:
  CARGO_TERM_COLOR: always

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v4
      - name: Install library
        run: pip install git+https://github.com/cmccomb/map-of-research.git -qqq
      - name: Copy old data out of the way
        run: cp data/* data_old/
      - name: Scrape the data
        run: scrape_faculty_data
      - name: Create the visualization
        run: visualize_faculty_data
      - name: Commit and push changes
        uses: actions-js/push@master
        with:
          github_token: ${{ secrets.token }}
